# Generated by Django 3.2.6 on 2023-12-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eksisozluk_entries',
            old_name='id',
            new_name='_id',
        ),
    ]
